name: Unit Tests
on:
  pull_request:
  push:
    branches:
        - 'master'

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: whiteducksoftware/azure-arm-action@v3.3
        id: deploy
        with:
            resourceGroupName: azurearmaction
            templateLocation: examples/template/template.json
            parameters: examples/template/parameters.json
            deploymentName: github-advanced-test

      - run: echo ${{ steps.deploy.outputs.containerName }}

      - uses: whiteducksoftware/azure-arm-action@v3.3
        id: deploy2
        with:
            resourceGroupName: azurearmaction
            templateLocation: examples/template/template.json
            parameters: examples/template/parameters.json
            deploymentName: github-advanced-test
            overrideParameters: |
              containerName=${{ steps.deploy.outputs.containerName }}-overriden
              
      - run: echo ${{ steps.deploy2.outputs.containerName }}