on:
  push:
    branches:
      - master

name: build-release

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: whiteduck/azure-arm-action
          auto_tag: true