on:
  push:
    branches:
      - master

name: build-release

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: build
        id: build
        uses: docker/build-action@v1
        with:
          repository: whiteduck/azure-arm-action
          tags: latest