on:
  push:
    branches:
      - master

name: build-release

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master